config/routes.rb
Rails.application.routes.draw do
  get 'users/showlogin'

  post 'users/login'

  resources :day_lives
  root "users#login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day_life.rb
class DayLife < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/day_lives_controller.rb
class DayLivesController < ApplicationController
  before_action :set_day_life, only: [:show, :edit, :update, :destroy]

  # GET /day_lives
  # GET /day_lives.json
  def index
    @day_lives = DayLife.all
  end

  # GET /day_lives/1
  # GET /day_lives/1.json
  def show
  end

  # GET /day_lives/new
  def new
    @day_life = DayLife.new
  end

  # GET /day_lives/1/edit
  def edit
  end

  # POST /day_lives
  # POST /day_lives.json
  def create
    @day_life = DayLife.new(day_life_params)

    respond_to do |format|
      if @day_life.save
        format.html { redirect_to @day_life, notice: 'Day life was successfully created.' }
        format.json { render :show, status: :created, location: @day_life }
      else
        format.html { render :new }
        format.json { render json: @day_life.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_lives/1
  # PATCH/PUT /day_lives/1.json
  def update
    respond_to do |format|
      if @day_life.update(day_life_params)
        format.html { redirect_to @day_life, notice: 'Day life was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_life }
      else
        format.html { render :edit }
        format.json { render json: @day_life.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_lives/1
  # DELETE /day_lives/1.json
  def destroy
    @day_life.destroy
    respond_to do |format|
      format.html { redirect_to day_lives_url, notice: 'Day life was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_life
      @day_life = DayLife.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_life_params
      params.require(:day_life).permit(:goal, :diary, :day, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    if logged_in?
      redirect_to day_lives_path
      return
    end
    @user = User.find_by_username(params[:users][:username].downcase)
    if @user && (@user.password == params[:users][:password])
      log_in @user
      # render html: [logged_in?, session[:user_id], user]
      redirect_to day_lives_path
    else
      flash.now[:invalid] = 'Tên đăng nhập hoặc mật khẩu không đúng.'
      render users_showlogin_path
    end
  end

  def showlogin
  end

  def log_in(user)
    session[:user_id] = user.id #lưu trong session id bởi user-id
  end
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
      !current_user.nil?
  end
  def log_out
      session.delete(:user_id)
      @current_user = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/day_lives_helper.rb
module DayLivesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/day_lives/_form.html.erb
<%= form_with(model: day_life, local: true) do |form| %>
  <% if day_life.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day_life.errors.count, "error") %> prohibited this day_life from being saved:</h2>

      <ul>
      <% day_life.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :goal %>
    <%= form.text_area :goal, id: :day_life_goal %>
  </div>

  <div class="field">
    <%= form.label :diary %>
    <%= form.text_area :diary, id: :day_life_diary %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day, id: :day_life_day %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :day_life_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/day_lives/edit.html.erb
<h1>Editing Day Life</h1>

<%= render 'form', day_life: @day_life %>

<%= link_to 'Show', @day_life %> |
<%= link_to 'Back', day_lives_path %>

app/views/day_lives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Day Lives</h1>

<table>
  <thead>
    <tr>
      <th>Goal</th>
      <th>Diary</th>
      <th>Day</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_lives.each do |day_life| %>
      <tr>
        <td><%= day_life.goal %></td>
        <td><%= day_life.diary %></td>
        <td><%= day_life.day %></td>
        <td><%= day_life.status %></td>
        <td><%= link_to 'Show', day_life %></td>
        <td><%= link_to 'Edit', edit_day_life_path(day_life) %></td>
        <td><%= link_to 'Destroy', day_life, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day Life', new_day_life_path %>

app/views/day_lives/new.html.erb
<h1>New Day Life</h1>

<%= render 'form', day_life: @day_life %>

<%= link_to 'Back', day_lives_path %>

app/views/day_lives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @day_life.goal %>
</p>

<p>
  <strong>Diary:</strong>
  <%= @day_life.diary %>
</p>

<p>
  <strong>Day:</strong>
  <%= @day_life.day %>
</p>

<p>
  <strong>Status:</strong>
  <%= @day_life.status %>
</p>

<%= link_to 'Edit', edit_day_life_path(@day_life) %> |
<%= link_to 'Back', day_lives_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dehabitat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/showlogin.html.erb
<%= form_for(:users,url: users_login_path, html: {id: 'login_form'}, method: 'post') do |form| %>   <!-- form đăng nhập -->
  <h1>Đăng nhập </h1>                                 
  <p>
      <%= form.label ('Tên đăng nhập:'), class: 'uname' %> <br/>
      <%= form.text_field :username %> <br/>
      <p id="errorUsername" class='error' ></p>
  </p>   
  <p>
      <%= form.label ('Mật khẩu:'), class: 'youpasswd' %> <br/>
      <%= form.password_field :password %> <br/>
      <p id="errorPassword" class='error'></p>
  </p>
  <p id="invalid" class='error'>
      
  </p>
  <p class="login button"> 
      <%= form.submit ('Đăng nhập') %>
  </p>
<% end %>